apiVersion: apps/v1
kind: Deployment
metadata:
  name: icesi-health-backend
  namespace: icesi-health
  labels:
    app: icesi-health-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icesi-health-backend
  template:
    metadata:
      labels:
        app: icesi-health-backend
    spec:
      containers:
      - name: icesi-backend
        image: azrk8s.azurecr.io/samples/icesiback
        imagePullPolicy: Always
        ports:
        - containerPort: 8089
        env:
          - name: DATABASE_URL
            value: "http://root:icesi-pass@$(MI_COUCHDB_SERVICE_HOST):5984"
            
---

apiVersion: v1
kind: Service
metadata:
  name: icesi-health-backend
  namespace: icesi-health
spec:
  selector:
    app: icesi-health-backend
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: ClusterIP
